### PR TITLE
9 UI frameworks added

### PR DESCRIPTION
**Pull request by code-guru**
Including: 
-    Flat UI
-    Responsive Grid System
-    Responsive GS
-    The Semantic GRID SYSTEM
-    Golden Grid System (GGS)
-    Titan Framework
-    Ingrid
-    Workless
-    Frameless

### CODE REVIEW

**Comment by diomed** [comment]
added some, that are still alive, manually.
may others RIP.

**Comment by code-guru** [comment]
what a classic persian community  😆 
could not get a simple pull request accepted after years

**Comment by afshinm** [comment]
@code-guru looks like you regret your decision and removed your comment :) 

> what a classic persian community  😆
> could not get a simple pull request accepted after years

that's fine though, as long as you understand that this is an open-source project, with MIT license and we don't guarantee anything.

**Comment by afshinm** [comment]
thanks @diomed

**Pull request closed without merging**
